### ISSUE TITLE
core initialization failed

### ISSUE THREAD

**Issue by robcza** [whalebone/KresMan#13]
It seems a race condition can result in a state where the core cache is never initialized.
```
2019-06-27 20:42:25,428 [19-1] INFO  [Kres.Man.Program.?] - Main
2019-06-27 20:42:25,456 [19-1] INFO  [Kres.Man.Program.?] - Init cache
2019-06-27 20:42:25,456 [19-1] INFO  [Kres.Man.Program.?] - Starting CoreClient Updater
2019-06-27 20:42:25,458 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 1 seconds..
2019-06-27 20:42:25,465 [19-5] INFO  [Kres.Man.CoreClient.?] - Starting CoreClient thread.
2019-06-27 20:42:25,478 [19-5] INFO  [Kres.Man.CoreClient.?] - GetCoreCacheLinux()
2019-06-27 20:42:25,632 [19-5] INFO  [Kres.Man.CoreClient.?] - Request
2019-06-27 20:42:26,459 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 2 seconds..
2019-06-27 20:42:27,459 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 3 seconds..
2019-06-27 20:42:27,979 [19-5] INFO  [Kres.Man.CoreClient.?] - GetStream
2019-06-27 20:42:27,979 [19-5] INFO  [Kres.Man.CoreClient.?] - ETag f3b89da01ab64c2fb3e7eed0cc318e7d is new, cache update process started.
2019-06-27 20:42:27,980 [19-5] INFO  [Kres.Man.CoreClient.?] - Deserialize.
2019-06-27 20:42:28,459 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 4 seconds..
2019-06-27 20:42:29,460 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 5 seconds..
2019-06-27 20:42:30,508 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 6 seconds..
2019-06-27 20:42:31,508 [19-1] INFO  [Kres.Man.CoreClient.?] - Loading Core cache, 7 seconds..
2019-06-27 20:42:32,290 [19-5] FATAL [Kres.Man.CoreClient.?] - System.NullReferenceException: Object reference not set to an instance of an object.
   at Kres.Man.CoreClient.GetCoreCacheLinux() in /app/CoreClient.cs:line 222
   at Kres.Man.CoreClient.ThreadProc() in /app/CoreClient.cs:line 40
```

**Comment by robcza** [comment]
it is possible that the cache file was not actually available in the cloud at that moment, still this has to be handled
