### ISSUE TITLE
accounting processing heavy workload errors

### ISSUE THREAD

**Issue by robcza** [whalebone/KresMan#24]
under heavy load of accounting packets we have reached this state:
```
2020-02-24 14:36:04,571 [1-21] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
2020-02-24 14:36:04,571 [1-21] DEBUG [Kres.Man.LightningRanger.?] - LMDB INS 162.95.241.25/32 437823862695 lu 162.95.241.25
2020-02-24 14:36:04,574 [1-27] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
2020-02-24 14:36:04,574 [1-27] DEBUG [Kres.Man.LightningRanger.?] - LMDB INS 194.162.117.84/32 735449689365 lu 194.162.117.84
2020-02-24 14:36:04,578 [1-27] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
2020-02-24 14:36:04,578 [1-27] DEBUG [Kres.Man.LightningRanger.?] - LMDB INS 211.177.106.152/32 623353421442 lu 211.177.106.152
2020-02-24 14:36:04,581 [1-27] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
2020-02-24 14:36:04,581 [1-27] DEBUG [Kres.Man.LightningRanger.?] - LMDB INS 101.242.254.208/32 367637635989 lu 101.242.254.208
2020-02-24 14:36:04,586 [1-27] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
2020-02-24 14:36:04,586 [1-27] DEBUG [Kres.Man.LightningRanger.?] - LMDB INS 36.188.147.133/32 253783748391 lu 36.188.147.133
2020-02-24 14:36:04,590 [1-21] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
2020-02-24 14:36:04,590 [1-21] DEBUG [Kres.Man.LightningRanger.?] - LMDB INS 82.222.69.68/32 885636499745 lu 82.222.69.68
2020-02-24 14:36:04,591 [1-26] ERROR [Kres.Man.RadiusServer.?] - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Kres.Man.RadiusServer.ProcessResult(Object args) bytes len=286
```

Private api for radius is not responding when this state is reached:
```
curl http://127.0.0.1:8080/radiusselect -d "{'address':'101.42.220.98'}"
```

**Comment by robcza** [comment]
probably a faulty test - crashing the whole interface
