### ISSUE TITLE
Verify Status during Cache Update

### ISSUE THREAD

**Issue by andronkyr** [whalebone/KresMan#26]
There are cases, e.g. network error, not-existing cache on repo, (please see below traces), where caches are not properly downloaded and pushed:

Example Cases:
* **Network Error**:
```
2020-08-18 08:58:49,195 [1-10] INFO  [Kres.Man.Cache.?] - GetCoreCacheLinux()
2020-08-18 08:59:29,363 [1-10] ERROR [Kres.Man.Cache.?] - System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Kres.Man.Cache.GetCoreCacheLinux()
   at Kres.Man.Cache.ThreadProc()
```
* **Not existing cache** : 
```
2020-08-11 10:58:31,732 [1-10] INFO  [Kres.Man.Cache.?] - GetCoreCacheLinux()
2020-08-11 10:58:31,984 [1-10] ERROR [Kres.Man.Cache.?] - System.IO.InvalidDataException: Central Directory corrupt.
 ---> System.IO.IOException: Invalid argument
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at Kres.Man.Cache.ExtractAndPush(Stream stream)
```
This results in kresman waiting for the update interval in order to request a new cache. 

Is it possible to check the status of the cache after the pulling and in case something has gone wrong, try again?

**Comment by Elctro** [comment]
Ok, kresman will now try 5 attempts, and it will fall back to the timeout wait after that.
curl http://127.0.0.1:8080/updatenow -d "{  }" 
this triggers cache update and skips the timeout
