### ISSUE TITLE
Updater intialization exception

### ISSUE THREAD

**Issue by robcza** [whalebone/KresMan#7]
Got this exception on kresman restart
```
Resolver ID is ---
2019-02-01 14:34:53,317 [19-1] INFO  [Kres.Man.Program.?] - Main
2019-02-01 14:34:53,340 [19-1] INFO  [Kres.Man.Program.?] - Init passive dns enricher
2019-02-01 14:34:53,341 [19-1] INFO  [Kres.Man.Program.?] - Init cache
2019-02-01 14:34:53,342 [19-1] INFO  [Kres.Man.Program.?] - Starting UDP Server
2019-02-01 14:34:53,344 [19-1] INFO  [Kres.Man.Program.?] - Starting CoreClient Updater
2019-02-01 14:34:53,345 [19-1] INFO  [Kres.Man.Program.?] - Starting Knot-Resolver Updater
2019-02-01 14:34:53,346 [19-1] INFO  [Kres.Man.Program.?] - Starting custom API
2019-02-01 14:34:53,357 [19-5] INFO  [Kres.Man.CoreClient.?] - Starting CoreClient thread.
2019-02-01 14:34:53,361 [19-6] INFO  [Kres.Man.KresUpdater.?] - Starting KresUpdater thread.
2019-02-01 14:34:53,361 [19-6] INFO  [Kres.Man.KresUpdater.?] - KresUpdater loop.
2019-02-01 14:34:53,362 [19-7] INFO  [Kres.Man.Listener.?] - Starting Listener thread.
2019-02-01 14:34:53,362 [19-7] INFO  [Kres.Man.Listener.?] - Starting listener http://127.0.0.1:8080/
2019-02-01 14:34:53,382 [19-3] DEBUG [Kres.Man.PassiveDNSEnricher.?] - processedLines=1325
2019-02-01 14:34:53,386 [19-5] INFO  [Kres.Man.CoreClient.?] - GetCoreCacheLinux()
2019-02-01 14:34:53,645 [19-5] INFO  [Kres.Man.CoreClient.?] - Request
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:80'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Production
Content root path: /app
Now listening on: https://0.0.0.0:443
Now listening on: http://0.0.0.0:80
Application started. Press Ctrl+C to shut down.
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
2019-02-01 14:34:54,009 [19-6] ERROR [Kres.Man.KresUpdater.?] - Newtonsoft.Json.JsonSerializationException: Error converting value "<base64 string>" to type 'System.Collections.Generic.IEnumerable`1[System.Byte]'. Path '8000391662.Proto_IpFrom', line 1, position 48. ---> System.ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.IEnumerable`1[System.Byte].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Kres.Man.KresUpdater.NourishUDPCache() in /app/KresUpdater.cs:line 333
```

**Comment by Elctro** [comment]
I need a copy of udp.cache file when this occurs again.
